[workspace.package]
name = "For_Sale"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["auction_game", "helper"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
ahash = "0.8.0"
rand = "0.9.0-alpha.2"
